server:
  port: 8082

spring:
  application:
    name: microservice-citasmedicas
  config:
    import: "optional:configserver:http://localhost:8888"

  data:
    mongodb:
      uri: mongodb+srv://telemedicina:1234@cluster0.6gknz23.mongodb.net/telemedicina_db?retryWrites=true&w=majority&appName=Cluster0


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
