server:
  port: 8081

spring:
  application:
    name: microservice-personas
  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: ${DB_TELE_URL}
    username: ${DB_TELE_USER}
    password: ${DB_TELE_PWD}
  jpa:
    hibernate:
      ddl_auto: create
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

